import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";

test("account activity explains debit and credit balances, exports evidence and clears stale results", async ({ page, request }) => {
  test.setTimeout(60000);
  const auth = { Authorization: `Basic ${Buffer.from("demo:demo-local-only").toString("base64")}` };
  async function post(path: string, data: object, key: string) {
    const csrf = await (await request.get("/api/csrf")).json();
    const response = await request.post(path, { headers: { ...auth, [csrf.headerName]: csrf.token, "Idempotency-Key": "account-activity-" + key }, data });
    expect(response.ok(), await response.text()).toBe(true);
    return (await response.json()).id as string;
  }
  const customer = await post("/api/customers", { name: "Cedar Accounts", email: "accounts@cedar.example" }, "customer");
  const vendor = await post("/api/vendors", { name: "Harbor", email: "accounts@harbor.example" }, "vendor");
  const invoice = (amount: string, date: string, key: string) => post("/api/invoices", { customerId: customer, description: `Design ${key}`, issuedOn: date, dueOn: date, amount }, key);
  const pay = (id: string, amount: string, date: string, key: string) => post(`/api/invoices/${id}/payments`, { paidOn: date, amount }, key);
  const old = await invoice("100.10", "2032-09-30", "old");
  await pay(old, "60.06", "2032-09-30", "opening-payment");
  const current = await invoice("200.20", "2032-10-01", "current");
  await pay(current, "25.25", "2032-10-31", "current-payment");
  const expense = await post("/api/expenses", { vendorId: vendor, description: "=2+2", spentOn: "2032-10-02", accountCode: "5100", amount: "10.10" }, "expense");
  const bill = await post("/api/bills", { vendorId: vendor, reference: "H1", description: "Supplies", issuedOn: "2032-10-01", dueOn: "2032-10-31", accountCode: "5000", amount: "40.04" }, "bill");
  await post(`/api/bills/${bill}/payments`, { paidOn: "2032-10-31", amount: "5.05" }, "bill-payment");
  await pay(current, "174.95", "2032-11-01", "future-payment");
  await post(`/api/expenses/${expense}/reverse`, { date: "2032-11-01" }, "future-reversal");
  const before = await (await request.get("/api/state", { headers: auth })).json();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/");
  await page.getByLabel("Username").fill("demo");
  await page.getByLabel("Password", { exact: true }).fill("demo-local-only");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await page.getByRole("button", { name: "Account activity", exact: true }).click();
  const result = page.locator(".account-activity-results");
  const account = page.getByRole("combobox", { name: "Ledger account", exact: true });
  const run = page.getByRole("button", { name: "Run account activity", exact: true });
  const exportButton = page.getByRole("button", { name: "Export account activity CSV", exact: true });
  await expect(exportButton).toHaveCount(0);
  await account.selectOption("1000");
  await page.getByLabel("Activity start", { exact: true }).fill("2032-10-01");
  await page.getByLabel("Activity end", { exact: true }).fill("2032-10-31");
  await run.click();
  for (const [label, amount] of [["Opening balance", "$60.06 Dr"], ["Period debits", "$25.25"], ["Period credits", "$15.15"], ["Closing balance", "$70.16 Dr"]])
    await expect(result.getByRole("row").filter({ hasText: label })).toContainText(amount);
  const movements = result.locator("tbody").nth(1).locator("tr");
  await expect(movements).toHaveCount(3);
  await movements.first().getByText("Posting references", { exact: true }).click();
  await expect(movements.first()).toContainText(expense);
  await expect(movements.first()).toContainText("$49.96 Dr");
  await page.screenshot({ path: "report-results/account-activity.png", fullPage: true });
  async function exported() {
    const downloading = page.waitForEvent("download"); await exportButton.click();
    const file = await downloading;
    expect(file.suggestedFilename()).toBe(`ledgerdesk-account-${await account.inputValue()}-${await page.getByLabel("Activity start", { exact: true }).inputValue()}-${await page.getByLabel("Activity end", { exact: true }).inputValue()}.csv`);
    return readFile((await file.path())!, "utf8");
  }
  const csv = await exported();
  expect(csv).toContain('"Opening balance","60.06"');
  expect(csv).toContain('"Closing balance","70.16"');
  expect(csv).toContain('"Period start","2032-10-01"');
  expect(csv).toContain('"Period end","2032-10-31"');
  expect(csv).toContain(expense);
  expect(csv).toContain("'=2+2");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const scroll = result.locator(".account-movements");
  expect(await scroll.evaluate((element) => { element.scrollLeft = element.scrollWidth; return element.scrollLeft; })).toBeGreaterThan(0);
  await page.screenshot({ path: "report-results/mobile-account-activity.png", fullPage: true });
  await account.selectOption("4000");
  await expect(result).toHaveCount(0); await expect(exportButton).toHaveCount(0);
  await run.click();
  await expect(result.getByRole("row").filter({ hasText: "Opening balance" })).toContainText("$100.10 Cr");
  await expect(result.getByRole("row").filter({ hasText: "Closing balance" })).toContainText("$300.30 Cr");
  expect(await exported()).toContain('"Closing balance","-300.30"');
  await page.getByLabel("Activity start", { exact: true }).fill("2032-10-02");
  await expect(exportButton).toHaveCount(0); await run.click();
  await expect(result).toContainText("No account postings in this period");
  await expect(result.getByRole("row").filter({ hasText: "Closing balance" })).toContainText("$300.30 Cr");
  await page.getByLabel("Activity end", { exact: true }).fill("2032-10-01");
  await run.click(); await expect(page.getByRole("alert")).toContainText("valid account activity period");
  await expect(exportButton).toHaveCount(0);
  await page.getByLabel("Activity end", { exact: true }).fill("2032-10-31");
  await page.route("**/api/reports/accounts/*/activity?*", (route) => route.fulfill({ status: 503, contentType: "application/json", body: "{}" }));
  await run.click(); await expect(page.getByRole("alert")).toContainText("could not be completed");
  await expect(result).toHaveCount(0); await expect(exportButton).toHaveCount(0);
  await page.unroute("**/api/reports/accounts/*/activity?*");
  await run.click(); await expect(result).toContainText("$300.30 Cr");
  await page.getByRole("button", { name: "Reload workspace", exact: true }).click();
  await expect(result).toHaveCount(0); await expect(exportButton).toHaveCount(0);
  await run.click();
  await page.getByRole("button", { name: "Single period reports", exact: true }).click();
  await expect(exportButton).toHaveCount(0);
  const after = await (await request.get("/api/state", { headers: auth })).json();
  expect(after.ledger).toEqual(before.ledger); expect(after.trialBalance).toEqual(before.trialBalance); expect(after.audit).toEqual(before.audit);
});
