import { test, expect } from "@playwright/test";

test("owners close, recover lost responses, inspect retained history and reopen without duplicates", async ({ page, request }) => {
  test.setTimeout(60000);
  const auth = { Authorization: `Basic ${Buffer.from("demo:demo-local-only").toString("base64")}` };
  async function post(path: string, data: object, key: string) {
    const csrf = await (await request.get("/api/csrf")).json();
    const response = await request.post(path, { headers: { ...auth, [csrf.headerName]: csrf.token, "Idempotency-Key": "year-end-control-" + key }, data });
    expect(response.ok(), await response.text()).toBe(true);
    return (await response.json()).id as string;
  }
  const records = async () => (await (await request.get("/api/year-end", { headers: auth })).json()).yearEndCloses;
  await post("/api/opening-bank-balance", { asOf: "2039-12-31", balance: "1000.25", memo: "Cleared opening" }, "opening");
  const vendor = await post("/api/vendors", { name: "Harbor", email: "accounts@harbor.example" }, "vendor");
  await post("/api/invoices", { customerId: "demo-customer", description: "Design", issuedOn: "2040-06-01", dueOn: "2040-06-30", amount: "100.10" }, "sale");
  await post("/api/bills", { vendorId: vendor, reference: "H1", description: "Supplies", issuedOn: "2040-06-01", dueOn: "2040-06-30", accountCode: "5000", amount: "40.04" }, "bill");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/"); await page.getByLabel("Username").fill("demo");
  await page.getByLabel("Password", { exact: true }).fill("demo-local-only");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await page.getByRole("button", { name: "Year-end preview", exact: true }).click();
  const run = page.getByRole("button", { name: "Run year-end preview", exact: true });
  const load = page.getByRole("button", { name: "Load closing history", exact: true });
  const result = page.locator(".year-end-results"), history = page.locator(".year-end-history");
  const close = page.getByRole("button", { name: "Close year-end earnings", exact: true });
  const note = page.getByLabel("Year-end review note", { exact: true });
  await load.click(); await expect(history).toContainText("No year-end closes");
  await page.getByRole("spinbutton", { name: "Calendar year", exact: true }).fill("2040");
  await run.click(); await expect(close).toBeDisabled();
  await post("/api/bank/reconciliations", { startsOn: "2040-01-01", endsOn: "2040-12-31", openingBalance: "1000.25", closingBalance: "1000.25" }, "bank");
  await post("/api/accounting-periods", { endsOn: "2040-12-31", reviewNote: "Reviewed annual books" }, "period");
  await page.getByRole("button", { name: "Reload workspace", exact: true }).click();
  await expect(result).toHaveCount(0); await run.click(); await expect(close).toBeDisabled();
  await note.fill("Reviewed documents and annual earnings");
  page.once("dialog", (dialog) => dialog.dismiss()); await close.click(); expect(await records()).toHaveLength(0);
  const writes: { path: string; key: string }[] = [];
  page.on("request", (r) => { if (r.method() === "POST" && r.url().includes("/api/year-end")) writes.push({ path: new URL(r.url()).pathname, key: r.headers()["idempotency-key"] }); });
  page.on("dialog", (dialog) => dialog.accept());
  await page.route("**/api/year-end", async (route) => {
    if (route.request().method() !== "POST") return route.continue();
    const response = await route.fetch(); expect(response.ok()).toBe(true);
    await route.fulfill({ status: 503, contentType: "application/json", body: "{}" });
  });
  await close.click(); await expect(page.getByRole("alert")).toContainText("could not be completed");
  await expect(note).toHaveValue("Reviewed documents and annual earnings");
  const original = (await records())[0]; expect(original.status).toBe("CLOSED");
  await page.unroute("**/api/year-end"); await close.click();
  await expect(page.getByRole("status")).toContainText("Year-end earnings closed");
  expect(writes[0].key).toBeTruthy(); expect(writes[1].key).toBe(writes[0].key); expect(await records()).toHaveLength(1);
  await expect(result).toHaveCount(0); await load.click();
  let row = history.locator(".year-end-history-record").first();
  await expect(row).toContainText("2040 · Closed");
  await row.getByText("Closing evidence references", { exact: true }).click();
  await expect(row).toContainText(original.id); await expect(row).toContainText(original.entry_id);
  await row.getByText("Retained earnings review", { exact: true }).click(); await expect(row).toContainText("Profit / loss $60.06");
  await page.screenshot({ path: "year-end-control-results/year-end-closing-history.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "year-end-control-results/mobile-year-end-closing-history.png", fullPage: true });
  await page.getByRole("button", { name: "Reopen earnings year 2040", exact: true }).click();
  const reason = page.getByLabel("Year-end reopening reason", { exact: true });
  const reopen = page.getByRole("button", { name: "Confirm earnings reopening", exact: true });
  await expect(reopen).toBeDisabled(); await reason.fill("Recheck missing supplier document");
  await page.route("**/api/year-end/*/reopen", async (route) => {
    const response = await route.fetch(); expect(response.ok()).toBe(true);
    await route.fulfill({ status: 503, contentType: "application/json", body: "{}" });
  });
  await reopen.click(); await expect(page.getByRole("alert")).toContainText("could not be completed");
  await expect(reason).toHaveValue("Recheck missing supplier document");
  const reopened = (await records())[0]; expect(reopened.status).toBe("REOPENED");
  expect(reopened.snapshot).toBe(original.snapshot); expect(reopened.reversal_entry_id).toBeTruthy();
  await page.unroute("**/api/year-end/*/reopen"); await reopen.click();
  await expect(page.getByRole("status")).toContainText("Supporting period and bank reviews remain closed");
  expect(writes[3].key).toBe(writes[2].key); expect((await records())[0].reversal_entry_id).toBe(reopened.reversal_entry_id);
  await load.click(); row = history.locator(".year-end-history-record").first();
  await expect(row).toContainText("2040 · Reopened"); await expect(row).toContainText("Recheck missing supplier document");
  await expect(page.getByRole("button", { name: "Reopen earnings year 2040", exact: true })).toHaveCount(0);
  await row.getByText("Closing evidence references", { exact: true }).click(); await expect(row).toContainText(reopened.reversal_entry_id);
  await row.getByText("Retained earnings review", { exact: true }).click(); await expect(row).toContainText("Profit / loss $60.06");
  await page.screenshot({ path: "year-end-control-results/year-end-reopened-history.png", fullPage: true });
  await run.click(); await expect(result).toContainText("Preview prerequisites met");
  await note.fill("Reviewed after reopening"); await close.click();
  await expect(page.getByRole("status")).toContainText("Year-end earnings closed");
  const all = await records(); expect(all).toHaveLength(2);
  expect(all.filter((r: { status: string }) => r.status === "CLOSED")).toHaveLength(1);
  expect(all.find((r: { id: string }) => r.id === original.id).snapshot).toBe(original.snapshot);
  await load.click(); await expect(history.locator(".year-end-history-record")).toHaveCount(2);
  await expect(page.getByRole("button", { name: "Reopen earnings year 2040", exact: true })).toHaveCount(1);
  await page.route("**/api/year-end", (route) => route.fulfill({ status: 503, contentType: "application/json", body: "{}" }));
  await load.click(); await expect(page.getByRole("alert")).toContainText("could not be completed");
  await expect(history.locator(".year-end-history-record")).toHaveCount(0);
  await page.unroute("**/api/year-end"); await load.click(); await expect(history.locator(".year-end-history-record")).toHaveCount(2);
  await page.getByRole("button", { name: "Reload workspace", exact: true }).click(); await expect(history.locator(".year-end-history-record")).toHaveCount(0);
  const report = await (await request.get("/api/reports?startsOn=2040-01-01&endsOn=2040-12-31", { headers: auth })).json();
  expect(report.profitLoss.netProfit).toBe("60.06"); expect(report.balanceSheet.difference).toBe("0.00");
});
