import { test, expect } from "@playwright/test";

test("year-end review explains prerequisites, exact closing proposals and clears stale results without posting", async ({ page, request }) => {
  test.setTimeout(60000);
  const auth = { Authorization: `Basic ${Buffer.from("demo:demo-local-only").toString("base64")}` };
  async function post(path: string, data: object, key: string) {
    const csrf = await (await request.get("/api/csrf")).json();
    const response = await request.post(path, { headers: { ...auth, [csrf.headerName]: csrf.token, "Idempotency-Key": "year-end-" + key }, data });
    expect(response.ok(), await response.text()).toBe(true);
    return (await response.json()).id as string;
  }
  await post("/api/opening-bank-balance", { asOf: "2032-12-31", balance: "1000.25", memo: "Cleared opening" }, "opening");
  const vendor = await post("/api/vendors", { name: "Harbor", email: "accounts@harbor.example" }, "vendor");
  const invoice = (amount: string, year: string, key: string) => post("/api/invoices", { customerId: "demo-customer", description: "Design", issuedOn: `${year}-06-01`, dueOn: `${year}-06-30`, amount }, key);
  const bill = (amount: string, year: string, key: string) => post("/api/bills", { vendorId: vendor, reference: key, description: "Supplies", issuedOn: `${year}-06-01`, dueOn: `${year}-06-30`, accountCode: "5000", amount }, key);
  await invoice("100.10", "2033", "sale"); await bill("40.04", "2033", "bill");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/");
  await page.getByLabel("Username").fill("demo");
  await page.getByLabel("Password", { exact: true }).fill("demo-local-only");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await page.getByRole("button", { name: "Year-end preview", exact: true }).click();
  const year = page.getByRole("spinbutton", { name: "Calendar year", exact: true });
  const run = page.getByRole("button", { name: "Run year-end preview", exact: true });
  const result = page.locator(".year-end-results");
  await expect(result).toHaveCount(0);
  await year.fill("2033"); await run.click();
  await expect(result).toContainText("Review needed before closing");
  await expect(result.locator(".year-end-blockers")).toContainText("accounting period close");
  await expect(result.locator(".year-end-blockers")).toContainText("bank reconciliation");
  const bank = await post("/api/bank/reconciliations", { startsOn: "2033-01-01", endsOn: "2033-12-31", openingBalance: "1000.25", closingBalance: "1000.25" }, "bank");
  const period = await post("/api/accounting-periods", { endsOn: "2033-12-31", reviewNote: "Reviewed annual books" }, "period");
  await invoice("10.10", "2034", "loss-sale"); await bill("20.20", "2034", "loss-bill");
  await invoice("90.90", "2036", "future-sale");
  const before = await (await request.get("/api/state", { headers: auth })).json();
  await page.getByRole("button", { name: "Reload workspace", exact: true }).click();
  await expect(result).toHaveCount(0); await run.click();
  await expect(result).toContainText("Preview prerequisites met");
  await expect(result.locator(".year-end-blockers")).toHaveCount(0);
  const earnings = result.getByRole("table", { name: "Annual earnings", exact: true });
  await expect(earnings.getByRole("row").filter({ hasText: "Net profit / loss" })).toContainText("$60.06");
  const proposed = result.getByRole("table", { name: "Proposed closing lines", exact: true });
  for (const [label, amount] of [["4000", "$100.10"], ["5000", "$40.04"], ["3300", "$60.06"]])
    await expect(proposed.getByRole("row").filter({ hasText: label })).toContainText(amount);
  await expect(proposed.getByRole("row").filter({ hasText: "Proposed totals" })).toHaveText(/Proposed totals\$100.10\$100.10/);
  await expect(result.getByRole("table", { name: "Temporary account balances" }).getByRole("row").filter({ hasText: "4000" })).toContainText("$100.10 Cr");
  await result.getByText("Year-end review references", { exact: true }).click();
  await expect(result.locator(".year-end-references")).toContainText(bank);
  await expect(result.locator(".year-end-references")).toContainText(period);
  await page.screenshot({ path: "year-end-results/year-end-preview.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(await result.locator(".year-end-balances").evaluate((element) => { element.scrollLeft = element.scrollWidth; return element.scrollLeft; })).toBeGreaterThan(0);
  await page.screenshot({ path: "year-end-results/mobile-year-end-preview.png", fullPage: true });
  await year.fill("2034"); await expect(result).toHaveCount(0); await run.click();
  await expect(result.locator(".year-end-blockers")).toContainText("before this year");
  await expect(earnings.getByRole("row").filter({ hasText: "Retained earnings change" })).toContainText("-$10.10");
  const retained = proposed.getByRole("row").filter({ hasText: "3300" });
  await expect(retained.getByRole("cell").nth(1)).toHaveText("$10.10");
  await expect(retained.getByRole("cell").nth(2)).toHaveText("$0.00");
  await year.fill("2035"); await expect(result).toHaveCount(0); await run.click();
  await expect(result).toContainText("No closing lines are proposed");
  await expect(result.locator(".year-end-blockers")).toContainText("before this year");
  await year.fill("0"); expect(await year.evaluate((element: HTMLInputElement) => element.checkValidity())).toBe(false);
  await year.fill("1.5"); expect(await year.evaluate((element: HTMLInputElement) => element.checkValidity())).toBe(false);
  await year.fill("2033");
  await page.route("**/api/year-end/preview?*", (route) => route.fulfill({ status: 503, contentType: "application/json", body: "{}" }));
  await run.click(); await expect(page.getByRole("alert")).toContainText("could not be completed");
  await expect(result).toHaveCount(0); await page.unroute("**/api/year-end/preview?*");
  let release!: () => void;
  const waiting = new Promise<void>((resolve) => { release = resolve; });
  await page.route("**/api/year-end/preview?*", async (route) => { await waiting; await route.continue(); });
  await run.click(); await expect(run).toBeDisabled(); await expect(year).toBeDisabled();
  await expect(page.getByRole("button", { name: "Account activity", exact: true })).toBeDisabled();
  release(); await expect(result).toContainText("Preview prerequisites met");
  await page.unroute("**/api/year-end/preview?*");
  await page.getByRole("button", { name: "Single period reports", exact: true }).click();
  await page.getByRole("button", { name: "Year-end preview", exact: true }).click();
  await expect(result).toHaveCount(0);
  const after = await (await request.get("/api/state", { headers: auth })).json();
  expect(after).toEqual(before);
});
